name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  # schedule:
  #   - cron: "14 3 1,8,15,22,29 * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Mount bazel cache
      uses: actions/cache@v1
      with:
        path: "/home/runner/.cache/bazel"
        key: bazel
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install -g npm@latest yarn@latest
    - run: yarn
    - run: yarn run build
    # - run: yarn run test
    - run: yarn run shutdown
