name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "14 3 1,8,15,22,29 * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: ngalaiko/bazel-action/1.2.1@1.2.1
      with:
        args: build //...
#    - uses: ngalaiko/bazel-action/1.2.1@1.2.1
#      with:
#        args: test //...
